budget-service:
  environment:
  - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
  - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
  - CONFIG_BUCKET=${CONFIG_BUCKET}  
  - DEPLOY_TARGET=${DEPLOY_TARGET}
  - PROJ_SETTINGS_DIR=${PROJ_SETTINGS_DIR}
  - DJANGO_SECRET_KEY=${DJANGO_SECRET_KEY}
  - DATABASE_ENGINE=${DATABASE_ENGINE}
  - DATABASE_NAME=${DATABASE_NAME}
  - DATABASE_HOST=${DATABASE_HOST}
  - DATABASE_PORT=5432
  - DATABASE_USER=${DATABASE_USER}
  - DATABASE_PASSWORD=${DATABASE_PASSWORD}

  build: .
  command: /code/test-in-docker.sh
  volumes:
    - .:/code
  ports:
    - "8000:8000"
